cloud:
  aws:
    credentials:
      access-key: AKIASQOIXWCQSH5ZFCLC
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false
application:
  bucket:
    name: trip-partner-user-profile
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB